# Generated by Django 4.1.7 on 2023-03-26 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100)),
                ('displayName', models.CharField(max_length=20)),
                ('photoURL', models.URLField(blank=True, null=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('value', models.FloatField(default=0)),
                ('typeTransaction', models.CharField(choices=[('tiêu dùng', 'spending'), ('thu nhập', 'income')], max_length=30)),
                ('idCategory', models.CharField(max_length=30)),
                ('note', models.TextField(blank=True, null=True)),
                ('imageDescription', models.URLField(blank=True, null=True)),
                ('date', models.DateTimeField()),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finace.user')),
            ],
        ),
    ]
