# Generated by Django 4.1.7 on 2023-03-28 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='typeTransaction',
            field=models.CharField(choices=[('tiêu dùng', 'spending'), ('thu nhập', 'income')], default='spending', max_length=30),
        ),
    ]
