# Generated by Django 4.1.7 on 2023-03-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finace', '0002_alter_transaction_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='money',
            field=models.FloatField(default=0),
        ),
    ]
