# Generated by Django 4.1.7 on 2023-03-28 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finace', '0003_user_money'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='money',
        ),
    ]
