# Generated by Django 4.1.7 on 2023-03-28 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finace', '0004_remove_user_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='typeTransaction',
            field=models.CharField(choices=[('spending', 'tiêu dùng'), ('income', 'thu nhập')], default='spending', max_length=30),
        ),
    ]
