# Generated by Django 4.1.7 on 2023-03-31 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finace', '0005_alter_transaction_typetransaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='uid',
            new_name='user_id',
        ),
    ]
